import { ThemeProvider } from "@/material-tailwind/page";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/layout/Header";
import { Footer } from "./components/layout/Footer";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify"; 
import GlobalProvider from "./Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "sHIPPING APP",
  description: "Generated by mAZOOR aHAMAD wYARA",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <GlobalProvider>
            <ToastContainer />
            <Header />

            <main className="min-h-[83vh]">
              {children}
            </main>

            <Footer />
          </GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
